on:
  workflow_dispatch:
    inputs:
      push:
        description: "Type 'yes' to push. Otherwise, only diff with remote is shown."
        required: true
        default: "show diff only"

name: "Push to Bioconductor"

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo ⬇️
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to Bioconductor
        run: |
          wd=$PWD
          #--- log setup: log everything in log/log.out
          mkdir -p log
          exec 1>log/log.out 2>&1
          set -ex
          #--- ssh setup
          mkdir ~/.ssh
          cp .github/config ~/.ssh/config
          cd ~/.ssh
          ssh-agent /bin/sh
          eval `ssh-agent -s`
          ssh-add - <<< "$SSH_KEY"
          ssh-keyscan $BIOC_HOST > ~/.ssh/known_hosts
          cd $wd
          #--- git config
          git config user.name '$MAINTAINER_NAME'
          git config user.email '$MAINTAINER_EMAIL'
          git remote add bioc git@git.bioconductor.org:packages/mixOmics.git
          #--- push
          git fetch --all # for logs in case of failure
          current_branch=${{ github.ref_name }}
          if [  "${{ github.event.inputs.push }}" == "yes" ]; then
            git push bioc $current_branch:$current_branch
          else
            git diff $current_branch -- bioc/$current_branch
          fi
        env:
          SSH_KEY: ${{ secrets.PRIVATE_SSH_KEY_BIOC_MAINTAINER }}
          BIOC_HOST: ${{ secrets.BIOC_HOST }}
          MAINTAINER_NAME: ${{ secrets.MAINTAINER_NAME }}
          MAINTAINER_EMAIL: ${{ secrets.MAINTAINER_EMAIL }}

      - name: Upload Logs
        if: always()
        uses: actions/upload-artifact@master
        with:
          name: log
          path: log
